#!/usr/bin/env bash
# Configure Nginx server so /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html
sed -i '54 i\
location /redirect_me {\
    return 301 https://github.com/;\
}' /etc/nginx/sites-available/default

sudo service nginx reload
