#!/usr/bin/env bash
# configures a brand new Ubuntu machine to add custom http response header
sudo sed -i '/# Basic Settings/a\\tadd_header X-Served-By '\$hostname';' /etc/nginx/nginx.conf
sudo service nginx reload
