#!/usr/bin/env bash
# configures a brand new Ubuntu machine to add custom http response header
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i '/listen 80 default_server/a\\tadd_header X-Served-By $hostname;' /etc/nginx/sites-enabled/default
sudo sed -i '/listen 80 default_server/a\\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo sed -i '/# Basic Settings/a\\tadd_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo service nginx start
