#!/usr/bin/env bash
# print BEST SCHOOL ten times
text="Best School"
i=1
while (( i <= 10 ))
do
    if ((i == 4))
    then
        echo "bad luck"
    elif (( i == 8 ))
    then
        echo "good luck"
    else
        echo "$text"
    fi
    ((i++))
done