#!/usr/bin/env bash
# print numbers from 1 to 20 with special messages for 4th, 9th, and 17th iterations
i=1
while (( i <= 20 ))
do
    case $i in
        4)
            echo "$i"
            echo "bad luck from China"
            ;;
        9)
            echo "$i"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$i"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$i"
            ;;
    esac
    ((i++))
done
