#!/usr/bin/env bash
# check school file
if [ -f "school" ];
then
    echo "school file exists"
    if [ -s "school" ];
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    echo "school is a regular file"
else
    echo "school file does not exist"    
fi